version: "3.9"

services:
  hello-world:
    image: $CONTAINER_REGISTRY_PATH/streamlit-apps/hello-world:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        # Hard limit
        limits:
          cpus: "0.5"
          memory: 100M
        # Soft limit
        reservations:
          cpus: "0.1"
          memory: 20M
      labels:
        - "traefik.http.routers.streamlit-hello-world.rule=Host(`ml.hosseinkhani.me`) && PathPrefix(`/streamlit/hello-world`)"
        - "traefik.http.services.streamlit-hello-world.loadbalancer.server.port=8501"
    environment:
      # The address where the server will listen for client and browser connections.
      # Use this if you want to bind the server to a specific address.
      # If set, the server will only be accessible from this address, and not from any aliases (like localhost).
      # Default: (unset)
      #STREAMLIT_SERVER_ADDRESS: ${STREAMLIT_SERVER_ADDRESS}
      # The base path for the URL where Streamlit should be served from.
      # Default: ""
      STREAMLIT_SERVER_BASE_URL_PATH: "/streamlit/hello-world"
      # Internet address where users should point their browsers in order to connect to the app. Can be IP address or DNS name and path.
      # This is used to: - Set the correct URL for CORS and XSRF protection purposes. - Show the URL on the terminal - Open the browser
      # Default: 'localhost'
      #STREAMLIT_BROWSER_SERVER_ADDRESS: ${STREAMLIT_BROWSER_SERVER_ADDRESS}
      # Whether to send usage statistics to Streamlit.
      # Default: true
      #STREAMLIT_BROWSER_GATHER_USAGE_STATS: ${STREAMLIT_BROWSER_GATHER_USAGE_STATS}
      # Database credentials
      DB_HOST_DATA: ${DB_HOST_DATA}
      DB_PORT_DATA: ${DB_PORT_DATA}
      DB_NAME_DATA: ${DB_NAME_DATA}
      DB_USER_DATA: ${DB_USER_DATA}
      DB_PASS_DATA: ${DB_PASS_DATA}
    networks:
      - traefik


networks:
  traefik:
    driver: overlay
    external: true
